name: CI

on:
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.rst'
  push:
    paths-ignore:
    - '**.md'
    - '**.rst'
    branches-ignore:
    - 'master'
    - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        emacs_version: [27.2, 28.2, 29.2]

    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/cache@v4
      id: cache-cask-packages
      with:
        path: .cask
        key: cache-cask-packages-000
    - uses: actions/cache@v4
      id: cache-cask-executable
      with:
        path: ~/.cask
        key: cache-cask-executable-000
    - uses: cask/setup-cask@master
      if: steps.cache-cask-executable.outputs.cache-hit != 'true'
      with:
        version: snapshot
    - run: echo "$HOME/.cask/bin" >> $GITHUB_PATH
    - name: compile
      run: make compile
