language: generic
env:
  matrix:
    - EMACS=emacs25
    - EMACS=emacs-snapshot

install:
  - if [ "$EMACS" = 'emacs25' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs25;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot;
    fi
  - $EMACS --version

script:
  - $EMACS -Q --batch -f batch-byte-compile eshell-z.el
  - $EMACS -Q --batch -L . -l ert -l eshell-z-test -f ert-run-tests-batch-and-exit
